-- Run this AFTER 20260914000000_initial_schema.sql AND
-- 20260915000000_bilingual_trade_names.sql have succeeded.
-- Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
--
-- (If you seeded trades before the bilingual migration existed, that migration
-- already backfilled name_es/name_en for you — don't re-run this trades insert,
-- it would create duplicates. This version is here for anyone setting up fresh.)

insert into service_categories (slug, name) values
  ('handyman', 'Handyman');

insert into trades (category_id, slug, name_es, name_en, sort_order)
select (select id from service_categories where slug = 'handyman'), slug, name_es, name_en, sort_order
from (values
  ('plumbing', 'Plomería', 'Plumbing', 1),
  ('electrical', 'Electricidad', 'Electrical', 2),
  ('hvac-ac', 'HVAC / Aire Acondicionado', 'HVAC / Air Conditioning', 3),
  ('concrete-masonry', 'Concreto / Albañilería', 'Concrete / Masonry', 4),
  ('carpentry', 'Carpintería', 'Carpentry', 5),
  ('roofing', 'Techado', 'Roofing', 6),
  ('painting', 'Pintura', 'Painting', 7),
  ('landscaping', 'Paisajismo', 'Landscaping', 8),
  ('appliance-repair', 'Reparación de Electrodomésticos', 'Appliance Repair', 9),
  ('general', 'General / No Estoy Seguro', 'General Handyman / Not Sure', 10)
) as t(slug, name_es, name_en, sort_order);

insert into pueblos (slug, name, sort_order) values
  ('adjuntas', 'Adjuntas', 1),
  ('aguada', 'Aguada', 2),
  ('aguadilla', 'Aguadilla', 3),
  ('aguas-buenas', 'Aguas Buenas', 4),
  ('aibonito', 'Aibonito', 5),
  ('anasco', 'Añasco', 6),
  ('arecibo', 'Arecibo', 7),
  ('arroyo', 'Arroyo', 8),
  ('barceloneta', 'Barceloneta', 9),
  ('barranquitas', 'Barranquitas', 10),
  ('bayamon', 'Bayamón', 11),
  ('cabo-rojo', 'Cabo Rojo', 12),
  ('caguas', 'Caguas', 13),
  ('camuy', 'Camuy', 14),
  ('canovanas', 'Canóvanas', 15),
  ('carolina', 'Carolina', 16),
  ('catano', 'Cataño', 17),
  ('cayey', 'Cayey', 18),
  ('ceiba', 'Ceiba', 19),
  ('ciales', 'Ciales', 20),
  ('cidra', 'Cidra', 21),
  ('coamo', 'Coamo', 22),
  ('comerio', 'Comerío', 23),
  ('corozal', 'Corozal', 24),
  ('culebra', 'Culebra', 25),
  ('dorado', 'Dorado', 26),
  ('fajardo', 'Fajardo', 27),
  ('florida', 'Florida', 28),
  ('guanica', 'Guánica', 29),
  ('guayama', 'Guayama', 30),
  ('guayanilla', 'Guayanilla', 31),
  ('guaynabo', 'Guaynabo', 32),
  ('gurabo', 'Gurabo', 33),
  ('hatillo', 'Hatillo', 34),
  ('hormigueros', 'Hormigueros', 35),
  ('humacao', 'Humacao', 36),
  ('isabela', 'Isabela', 37),
  ('jayuya', 'Jayuya', 38),
  ('juana-diaz', 'Juana Díaz', 39),
  ('juncos', 'Juncos', 40),
  ('lajas', 'Lajas', 41),
  ('lares', 'Lares', 42),
  ('las-marias', 'Las Marías', 43),
  ('las-piedras', 'Las Piedras', 44),
  ('loiza', 'Loíza', 45),
  ('luquillo', 'Luquillo', 46),
  ('manati', 'Manatí', 47),
  ('maricao', 'Maricao', 48),
  ('maunabo', 'Maunabo', 49),
  ('mayaguez', 'Mayagüez', 50),
  ('moca', 'Moca', 51),
  ('morovis', 'Morovis', 52),
  ('naguabo', 'Naguabo', 53),
  ('naranjito', 'Naranjito', 54),
  ('orocovis', 'Orocovis', 55),
  ('patillas', 'Patillas', 56),
  ('penuelas', 'Peñuelas', 57),
  ('ponce', 'Ponce', 58),
  ('quebradillas', 'Quebradillas', 59),
  ('rincon', 'Rincón', 60),
  ('rio-grande', 'Río Grande', 61),
  ('sabana-grande', 'Sabana Grande', 62),
  ('salinas', 'Salinas', 63),
  ('san-german', 'San Germán', 64),
  ('san-juan', 'San Juan', 65),
  ('san-lorenzo', 'San Lorenzo', 66),
  ('san-sebastian', 'San Sebastián', 67),
  ('santa-isabel', 'Santa Isabel', 68),
  ('toa-alta', 'Toa Alta', 69),
  ('toa-baja', 'Toa Baja', 70),
  ('trujillo-alto', 'Trujillo Alto', 71),
  ('utuado', 'Utuado', 72),
  ('vega-alta', 'Vega Alta', 73),
  ('vega-baja', 'Vega Baja', 74),
  ('vieques', 'Vieques', 75),
  ('villalba', 'Villalba', 76),
  ('yabucoa', 'Yabucoa', 77),
  ('yauco', 'Yauco', 78);
